### ISSUE TITLE
Minor Bug: Typo on line 99 in garnet_tool.gleam

### ISSUE THREAD

**Issue by Apollo-XIV** [Comamoca/garnet#2]
Was trying out this library and it seems super useful! No binary compilation was a big downside for me for learning gleam but this helps massively. I'm hoping this isn't inappropriate but I noticed a typo when compile fails and found it in the source code. The error message on line 99 of garnet_tool.gleam is currently misspelled 'Compile faied' instead of 'Compile failed' with an 'l'.

**Comment by Comamoca** [comment]
Thank you!

I'm not a native speaker of English, so issues like this are very helpful for me.
If you find any similar issues, please let me know again! 😃

> No binary compilation was a big downside for me for learning gleam but this helps massively.

I was thinking the same thing and created this program.

At first I tried to use [burrito-elixir/burrito](https://github.com/burrito-elixir/burrito) from Gleam, but it was too difficult for me at the time and I gave up.

It's a shame that I can't use Erlang's rich libraries, so I'd like to try again someday.
